# Game
GAME_TICKS_PER_SECOND = 20
GAME_OFFSET_PER_POSITION = 100

# Player
PLAYER_BOMB = 3
PLAYER_POWER = 2
PLAYER_SPEED = int(GAME_OFFSET_PER_POSITION / GAME_TICKS_PER_SECOND * 2)  # 1 sec to cross two cases
PLAYER_START_WITH_MINE = False
PLAYER_START_WITH_HAMMER = False

# Bomb
BOMB_FUSE_TIME = 3 * GAME_TICKS_PER_SECOND
BOMB_SPEED = PLAYER_SPEED * 2

# Map
MAP_VOID = " "
MAP_WALL = "#"
MAP_BOMB = "*"
MAP_MINE = "+"
MAP_BRICK = "&"
MAP_POWERUP_BOMB = "B"
MAP_POWERUP_MINE = "M"
MAP_POWERUP_POWER = "P"
MAP_POWERUP_SPEED = "S"
MAP_POWERUP_HAMMER = "H"

MAP_BRICK_TO_VOID_RATIO = 0.2
MAP_BRICK_TO_POWERUP_RATIO = 0.4

# Powerups
POWERUPS = [
    (MAP_POWERUP_BOMB, 3),
    (MAP_POWERUP_MINE, 1),
    (MAP_POWERUP_POWER, 3),
    (MAP_POWERUP_SPEED, 3),
    (MAP_POWERUP_HAMMER, 1)
]

# Please do not modify
VECTORS = {
    "N": (0, -1),
    "E": (1, 0),
    "S": (0, 1),
    "W": (-1, 0)
}
